// GENERATED by scripts/generate-eql-api-docs.ts from the EQL release manifest.
// Do not edit; the prebuild step overwrites it with the version of the EQL
// release the docs are built against.
export const EQL_VERSION = "3.0.0-sample";
