#!/usr/bin/env tsx
/**
 * Content API gate.
 *
 * Fails the build when documentation teaches an API that is deprecated, was
 * removed, or never existed. Two long-lived content branches plus a fast-moving
 * SDK means a page fixed on one branch can be silently reintroduced by a port
 * from the other — which is exactly how the deprecated `LockContext.identify()`
 * flow survived a fix and came back in a comparison-page port.
 *
 * Run via `bun run validate-content`; wired into prebuild.
 *
 * A line is exempt if it also says the API is retired ("deprecated", "removed",
 * "no longer", "are gone"), so that callouts and migration notes are free to
 * name the old API in order to warn readers off it. The check is deliberately
 * line-local: naming a dead symbol without saying it is dead is the bug.
 *
 * Generated output is skipped: it mirrors the SDK's own doc comments, which we
 * fix upstream rather than here.
 */
import fs from "node:fs";
import path from "node:path";

/** Generated by scripts/*, or a version reference that documents old syntax on purpose. */
const SKIP_PATHS = [
  "content/stack/reference/stack/", // TypeDoc output
  "content/docs/reference/stack/", // TypeDoc output (post-repoint)
  "content/stack/reference/eql/index.mdx", // generated EQL API reference
  "content/docs/reference/eql/functions.mdx", // generated
  "content/docs/reference/cli/", // generated from `stash manifest --json`
  "content/docs/reference/eql/v2/", // the retained EQL v2 reference
];

/**
 * Prose that names a retired API in order to warn readers off it. Kept narrow:
 * these are the words we actually use in deprecation callouts and migration
 * notes, not a general escape hatch.
 */
const RETIRED_MARKER =
  /\b(deprecat\w*|removed|no longer|are gone|was gone|never existed)\b/i;

type Rule = {
  id: string;
  pattern: RegExp;
  message: string;
  fix: string;
  /** Only apply the rule to files under these prefixes. */
  scope: string[];
};

const IDENTITY_SCOPE = ["content/docs/", "content/stack/"];
/** The legacy tree documents EQL v2 throughout; only the v2 IA must be v3-only. */
const V3_SCOPE = ["content/docs/"];

const RULES: Rule[] = [
  {
    id: "lockcontext-identify",
    pattern: /\.identify\s*\(/,
    message:
      "`LockContext.identify()` is deprecated. Per-operation CTS tokens were removed in protect-ffi 0.25; the token it fetches no longer affects encryption.",
    fix: 'Authenticate the client with `OidcFederationStrategy` via `config.authStrategy`, then pass the claim to `.withLockContext({ identityClaim: ["sub"] })`.',
    scope: IDENTITY_SCOPE,
  },
  {
    id: "identity-token-option",
    pattern: /identityToken\s*:/,
    message:
      "`withLockContext({ identityToken })` has never existed in any released version of @cipherstash/stack.",
    fix: 'Use `.withLockContext({ identityClaim: ["sub"] })` on the operation, not on the client.',
    scope: IDENTITY_SCOPE,
  },
  {
    id: "bare-lockcontext-constructor",
    pattern: /new\s+LockContext\s*\(\s*\)/,
    message:
      "A bare `new LockContext()` is only useful with the deprecated `identify()` flow.",
    fix: 'Pass a plain `{ identityClaim: ["sub"] }` to `.withLockContext()`. The Supabase query builder still requires an instance: `new LockContext({ context: { identityClaim: ["sub"] } })`.',
    scope: IDENTITY_SCOPE,
  },
  {
    id: "eql-v2-encrypted-type",
    pattern: /\beql_v2_encrypted\b/,
    message: "The `eql_v2_encrypted` column type was removed in EQL 3.0.0.",
    fix: "Type the column with an EQL v3 domain variant, e.g. `public.text_eq`. See /reference/eql/core-concepts.",
    scope: V3_SCOPE,
  },
  {
    id: "eql-v2-schema-functions",
    pattern: /\beql_v2\.\w+\s*\(/,
    message: "The `eql_v2` schema was removed in EQL 3.0.0.",
    fix: "Use the `eql_v3` equivalents, or the encrypted operators directly with a typed operand.",
    scope: V3_SCOPE,
  },
  {
    id: "eql-v2-config-table",
    pattern:
      /\b(cs_add_column_v1|cs_match_v1|cs_ste_vec_v2|cs_check_encrypted_v1|add_search_config|config_add_column|config_add_table)\b/,
    message:
      "EQL v3 has no database-side configuration table; these functions are gone.",
    fix: "A column's searchable capability is fixed by the domain variant it is typed as. See /reference/eql/core-concepts.",
    scope: V3_SCOPE,
  },
  {
    id: "protect-branding",
    pattern: /\b(ProtectClientConfig|@cipherstash\/cli)\b/,
    message:
      "Stale naming from before the `protect` -> `stack` rename, or the `@cipherstash/cli` -> `stash` rename.",
    fix: "Use `EncryptionClientConfig` and `stash`.",
    scope: V3_SCOPE,
  },
];

type Finding = {
  file: string;
  line: number;
  rule: Rule;
  text: string;
};

function collectFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  const files: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...collectFiles(full));
    else if (/\.mdx?$/.test(entry.name)) files.push(full);
  }
  return files;
}

function isSkipped(relative: string): boolean {
  return SKIP_PATHS.some((prefix) => relative.startsWith(prefix));
}

function inScope(relative: string, rule: Rule): boolean {
  return rule.scope.some((prefix) => relative.startsWith(prefix));
}

const root = process.cwd();
const findings: Finding[] = [];

for (const dir of ["content/docs", "content/stack"]) {
  for (const file of collectFiles(path.join(root, dir))) {
    const relative = path.relative(root, file).split(path.sep).join("/");
    if (isSkipped(relative)) continue;

    const lines = fs.readFileSync(file, "utf8").split("\n");
    lines.forEach((text, i) => {
      // A line that names a dead API *and says it is dead* is doing its job.
      if (RETIRED_MARKER.test(text)) return;

      for (const rule of RULES) {
        if (!inScope(relative, rule)) continue;
        if (rule.pattern.test(text)) {
          findings.push({
            file: relative,
            line: i + 1,
            rule,
            text: text.trim(),
          });
        }
      }
    });
  }
}

if (findings.length > 0) {
  const byRule = new Map<string, Finding[]>();
  for (const f of findings) {
    const list = byRule.get(f.rule.id) ?? [];
    list.push(f);
    byRule.set(f.rule.id, list);
  }

  console.error(
    `✗ ${findings.length} occurrence(s) of deprecated or non-existent API in documentation:\n`,
  );
  for (const [id, group] of byRule) {
    const { message, fix } = group[0].rule;
    console.error(`  [${id}] ${message}`);
    console.error(`  Fix: ${fix}\n`);
    for (const f of group) {
      console.error(`    ${f.file}:${f.line}`);
      console.error(`      ${f.text.slice(0, 100)}`);
    }
    console.error("");
  }
  console.error(
    'A line that also says the API is retired ("deprecated", "removed", "no longer",\n' +
      '"are gone", "never existed") is exempt, so deprecation callouts still pass.',
  );
  process.exit(1);
}

console.log("✓ no deprecated or non-existent API found in documentation");
